before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./cmd/bloops-cli
    id: cli
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: bloops-cli
archives:
  - replacements:
      darwin: MacOSX
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: robotomize
    name: bloops