name: Bloops
on:
  push:
    branches:
      - main

jobs:
  regular_build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build \
          -trimpath \
          -ldflags "-s -w -X main.version=$(git describe --tags --abbrev=0) -extldflags '-static'" \
          -installsuffix cgo \
          -tags netgo \
          -o /app/bot \
          ./cmd/bloopsbot-srv

      - name: Test
        run: go test -v ./...

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --config .goreleaser.yml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            robotomize/bloops:latest

      - name: Send a message to Telegram
        uses: robotomize/notify-telegram@v0.2.4
        with:
          chat: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          status: ${{ job.status }}
          message: "Build complete"